# Generated by Django 3.2.12 on 2022-03-22 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detailDirectory',
            fields=[
                ('detail_directory_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail_directory_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'detail_directories',
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('area', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('is_connect', models.BooleanField(default=False)),
                ('expert_description', models.CharField(max_length=200)),
                ('review_count', models.IntegerField(default=0)),
                ('level', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'expert',
            },
        ),
        migrations.CreateModel(
            name='mainDirectory',
            fields=[
                ('main_directory_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_directory_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'main_directories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('job_type', models.CharField(max_length=10, null=True)),
                ('job_sector', models.CharField(max_length=20, null=True)),
                ('user_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('profile_image', models.URLField(max_length=2000, null=True)),
                ('phone_number', models.CharField(default='00000000000', max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='subDirectory',
            fields=[
                ('sub_directory_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_directory_name', models.CharField(max_length=10)),
                ('main_directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.maindirectory')),
            ],
            options={
                'db_table': 'sub_directories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=20)),
                ('image_url', models.URLField()),
                ('request_count', models.IntegerField()),
                ('detail_directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.detaildirectory')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(default='Good', max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mainApp.expert')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.user')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='expert',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.user'),
        ),
        migrations.AddField(
            model_name='detaildirectory',
            name='sub_directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subdirectory'),
        ),
    ]
