# Generated by Django 3.2.12 on 2022-03-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='expert',
        ),
        migrations.AddField(
            model_name='service',
            name='service',
            field=models.ManyToManyField(related_name='service', to='mainApp.Expert'),
        ),
    ]
