# Generated by Django 3.2.12 on 2022-03-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='heart_count',
            field=models.IntegerField(default=0),
        ),
    ]
