# Generated by Django 3.2.12 on 2022-03-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_product_heart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='price_sum',
            field=models.IntegerField(default=0),
        ),
    ]
