# Generated by Django 3.2.12 on 2022-03-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20220329_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service',
        ),
    ]
